// zh-HK / English strings for CYBER BOARD (registered with the local i18n layer).
import { addStrings } from './i18n.js';
addStrings({
  title: ['賽博棋鬥', 'CYBER BOARD'], kicker: ['霓虹九龍 · 四合一棋盤對戰', 'NEON KOWLOON · 4-IN-1 BOARD BATTLES'],
  tagline: ['四款經典棋盤遊戲，食子即開打！每次吃子都會觸發 3D 霓虹對決動畫。', 'Four classic board games — every capture triggers a 3D neon battle cinematic.'],
  pickGame: ['揀遊戲', 'CHOOSE A GAME'],
  'g.chess': ['國際象棋', 'CHESS'], 'g.chess.sub': ['王車易位・吃過路兵・升變', 'castling · en passant · promotion'],
  'g.xiangqi': ['中國象棋', 'XIANGQI'], 'g.xiangqi.sub': ['楚河漢界・炮打隔山', 'river · palace · cannon screens'],
  'g.flip': ['黑白棋', 'FLIP'], 'g.flip.sub': ['夾住即翻・連鎖閃電', 'outflank · chain-lightning flips'],
  'g.sky': ['飛行棋', 'SKY RACE'], 'g.sky.sub': ['擲骰起飛・空戰擊落', 'roll · launch · dogfight'],
  bestFloor: ['最高 {n} 層', 'BEST F{n}'], noFloor: ['未挑戰', 'NEW'],
  chips: ['晶片', 'CHIPS'],
  endless: ['無盡之塔', 'ENDLESS TOWER'], endlessSub: ['第 {n} 層 · 最佳 {b}', 'FLOOR {n} · BEST {b}'],
  vsAi: ['對戰電腦', 'VS AI'], local2p: ['雙人同機', 'LOCAL 2P'], local2pSub: ['輪流用同一部機', 'pass and play'],
  difficulty: ['難度', 'DIFFICULTY'], opponent: ['對手', 'OPPONENT'],
  players: ['玩家數', 'PLAYERS'], humans: ['真人', 'HUMANS'], planes: ['每人飛機', 'PLANES'],
  back: ['返回', 'BACK'], start: ['開始', 'START'], settings: ['設定', 'SETTINGS'], close: ['關閉', 'CLOSE'],
  language: ['語言', 'LANGUAGE'], battleFx: ['吃子對決動畫', 'CAPTURE BATTLES'], fxFull: ['完整', 'FULL'], fxQuick: ['快速', 'QUICK'], fxOff: ['關閉', 'OFF'],
  sound: ['音效', 'SOUND'], music: ['音樂', 'MUSIC'], haptics: ['震動', 'HAPTICS'], hints: ['提示落點', 'MOVE HINTS'], rotate2p: ['雙人時轉棋盤', 'ROTATE BOARD IN 2P'], on: ['開', 'ON'], off: ['關', 'OFF'],
  privacy: ['私隱政策', 'Privacy'],
  paused: ['已暫停', 'PAUSED'], resume: ['繼續', 'RESUME'], restart: ['重新開始', 'RESTART'], quit: ['離開', 'QUIT'],
  you: ['你', 'YOU'], p1: ['玩家一', 'PLAYER 1'], p2: ['玩家二', 'PLAYER 2'], player: ['玩家 {n}', 'PLAYER {n}'], ai: ['電腦', 'AI'],
  yourTurn: ['到你', 'YOUR MOVE'], turnOf: ['{n} 嘅回合', "{n}'S TURN"], thinking: ['{n} 諗緊…', '{n} IS THINKING…'],
  check: ['將軍！', 'CHECK!'], checkmate: ['將死！', 'CHECKMATE!'], stalemate: ['困斃', 'STALEMATE'], pass: ['無子可落 · 跳過', 'NO MOVE · PASS'],
  rollDice: ['擲骰', 'ROLL'], tapPlane: ['揀一架飛機', 'PICK A PLANE'], noMove: ['冇得行', 'NO MOVE'], extraRoll: ['擲到 6！再擲一次', 'ROLLED 6 — ROLL AGAIN'], threeSix: ['三次 6 · 回合結束', 'THREE 6s · TURN LOST'],
  boost: ['加速！', 'BOOST!'], home: ['返到基地！', 'HOME!'], launch: ['起飛！', 'TAKE OFF!'], corner: ['奪角！', 'CORNER!'], chain: ['{n} 連翻', '{n}× CHAIN'],
  promote: ['升變', 'PROMOTE'], promoted: ['升變！', 'PROMOTION!'],
  undo: ['悔棋', 'UNDO'], hint: ['提示', 'HINT'], emote: ['表情', 'EMOTE'], pause: ['暫停', 'PAUSE'], mute: ['靜音', 'MUTE'],
  undoAsk: ['睇段廣告就可以悔棋？', 'Watch an ad to undo?'], hintAsk: ['睇段廣告攞提示？', 'Watch an ad for a hint?'], reviveAsk: ['睇段廣告重試呢層？', 'Watch an ad to retry this floor?'],
  watchAd: ['睇廣告', 'WATCH AD'], noThanks: ['唔使喇', 'NO THANKS'], free: ['免費', 'FREE'],
  win: ['勝利！', 'VICTORY!'], lose: ['落敗', 'DEFEAT'], draw: ['和局', 'DRAW'], floorClear: ['第 {n} 層 突破！', 'FLOOR {n} CLEARED!'], floorFail: ['挑戰失敗', 'FLOOR FAILED'],
  winnerIs: ['{n} 勝出！', '{n} WINS!'],
  'r.checkmate': ['將死', 'Checkmate'], 'r.stalemate': ['困斃（無子可走）', 'Stalemate'], 'r.repetition': ['三次重複局面', 'Threefold repetition'], 'r.fifty': ['長時間冇吃子', 'Move-limit rule'], 'r.material': ['子力不足', 'Insufficient material'],
  'r.count': ['{a} : {b}', '{a} : {b}'], 'r.race': ['全部飛機返到基地', 'All planes home'], 'r.target': ['完成目標', 'Objective complete'], 'r.limit': ['步數用晒', 'Out of moves'], 'r.objective': ['目標未完成', 'Objective not met'],
  next: ['下一層', 'NEXT FLOOR'], rematch: ['再嚟一局', 'REMATCH'], retry: ['重試', 'RETRY'], revive: ['復活重試', 'REVIVE & RETRY'], menu: ['主畫面', 'MAIN MENU'], newRecord: ['★ 新紀錄 ★', '★ NEW RECORD ★'],
  checkpoint: ['檢查點：第 {n} 層', 'CHECKPOINT: FLOOR {n}'], milestone: ['里程碑！解鎖新外觀', 'MILESTONE! NEW SKIN UNLOCKED'], chipsGained: ['+{n} 晶片', '+{n} CHIPS'],
  floor: ['第 {n} 層', 'FLOOR {n}'], boss: ['首領戰', 'BOSS'],
  'obj.duel': ['擊敗對手', 'Defeat your rival'], 'obj.rush': ['{m} 步內吃 {t} 隻子', 'Capture {t} pieces in {m} moves'], 'obj.endgame': ['{m} 步內將死對手', 'Checkmate within {m} moves'],
  'obj.margin': ['贏 {t} 隻子或以上', 'Win by {t}+ discs'], 'obj.corners': ['佔 {t} 個角兼贏', 'Take {t} corners and win'], 'obj.race': ['第一個返基地', 'First to bring every plane home'], 'obj.hunter': ['擊落 {t} 架兼贏', 'Shoot down {t} and win'],
  'hud.rush': ['吃子 {c}/{t} · 剩 {m} 步', 'CAPTURES {c}/{t} · {m} LEFT'], 'hud.endgame': ['剩 {m} 步', '{m} MOVES LEFT'], 'hud.hunter': ['擊落 {c}/{t}', 'DOWNED {c}/{t}'], 'hud.corners': ['角 {c}/{t}', 'CORNERS {c}/{t}'],
  demo: ['DEMO · 自動示範', 'DEMO · AUTOPLAY'], skip: ['撳一下跳過', 'TAP TO SKIP'],
  'e.nice': ['好嘢！', 'NICE!'], 'e.ez': ['冇難度', 'TOO EASY'], 'e.yikes': ['大鑊！', 'YIKES!'], 'e.gg': ['GG', 'GG'],
  'col.0': ['青', 'CYAN'], 'col.1': ['紫紅', 'MAGENTA'], 'col.2': ['金', 'GOLD'], 'col.3': ['綠', 'GREEN'],
  'side.white': ['白方', 'WHITE'], 'side.black': ['黑方', 'BLACK'], 'side.red': ['紅方', 'RED'], 'side.blackxq': ['黑方', 'BLACK'], 'side.cyan': ['青方', 'CYAN'], 'side.magenta': ['紫方', 'MAGENTA'],
  'p.chess.1': ['兵', 'Pawn'], 'p.chess.2': ['馬', 'Knight'], 'p.chess.3': ['象', 'Bishop'], 'p.chess.4': ['車', 'Rook'], 'p.chess.5': ['后', 'Queen'], 'p.chess.6': ['王', 'King'],
  'p.xq.1': ['帥', 'General'], 'p.xq.2': ['仕', 'Advisor'], 'p.xq.3': ['相', 'Elephant'], 'p.xq.4': ['馬', 'Horse'], 'p.xq.5': ['車', 'Chariot'], 'p.xq.6': ['炮', 'Cannon'], 'p.xq.7': ['兵', 'Soldier'],
  plane: ['戰機', 'Jet'], skin: ['棋子外觀', 'PIECE SKIN'], skinLocked: ['第 {n} 層解鎖', 'Unlocks at floor {n}'],
  rulesTitle: ['規則', 'RULES'],
  'rules.chess': ['標準國際象棋：王車易位、吃過路兵、升變（可揀）、將死／困斃、三次重複、五十步、子力不足和局。', 'Standard chess: castling, en passant, promotion (choice), checkmate / stalemate, threefold repetition, 50-move rule, insufficient material.'],
  'rules.xiangqi': ['九宮、楚河、將帥不能對面、炮要隔一子先食到、蹩馬腳、塞象眼。無子可走（困斃）都當輸。三次重複局面或 60 回合冇吃子＝和局。', 'Palace, river, flying-general rule, cannon needs one screen to capture, horse-leg and elephant-eye blocks. No legal move = loss (stalemate too). Threefold repetition or 60 moves without a capture = draw.'],
  'rules.flip': ['落子要夾住對方一行，夾住嘅全部翻轉。冇得落就跳過，雙方都冇得落就計數。', 'Place to outflank a line of enemy discs — they all flip. No move = pass; when neither side can move, most discs wins.'],
  'rules.sky': ['擲 6 先可以起飛（擲 6 再擲一次，連續三次 6 就冇得行）。準確步數先返到基地。停喺同色格會加速跳 4 格。降落喺敵機上面就擊落佢返機庫（起飛格安全）。', 'Roll a 6 to launch (a 6 rolls again; three 6s in a row lose the turn). Exact roll to reach home. Landing on your own colour boosts 4 squares. Land on an enemy jet to shoot it back to its hangar (start squares are safe).'],
  loading: ['棋盤啟動中…', 'BOOTING THE BOARD…'],
  score: ['比數', 'SCORE'], 'st.captures': ['吃子', 'CAPTURES'], 'st.moves': ['回合', 'MOVES'], 'st.discs': ['你嘅棋子', 'YOUR DISCS'], 'st.chain': ['最長連翻', 'BEST CHAIN'],
  'st.corners': ['佔角', 'CORNERS'], 'st.kills': ['擊落', 'SHOT DOWN'], 'st.lost': ['被擊落', 'LOST'],
});
